version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "src/hello.restaurant.api.csproj" }}
      - run:
          name: "install project dependencies"
          command: dotnet restore
      - save_cache:
          paths:
            - c:\users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/hello.restaurant.api.csproj" }}
      #- run:
          # name: "run application unit tests"
          # command: dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage"
          # command: dotnet test
      # - store_artifacts:
          # path: c:\users\circleci\project\test_coverage
  build:
    description: build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "build application according to some given configuration"
          command: dotnet build --configuration Release
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test